### ISSUE TITLE
s.info([...]) and s.fetch(...) choke when there are too many jobs/sessions running at CANFAR

### ISSUE THREAD

**Issue by aaronpearlman** [CHIMEFRB/skaha#11]
`s.fetch(kind="headless")` and `s.info([session_id1, session_id2, ..., session_idN])` both choke and fail when there are too many jobs or sessions

**Comment by shinybrar** [comment]
Can you provide some more context,

1. How many sessions / jobs seems to be the threshold
2. Are you using the Session or the Sessions API

**Comment by aaronpearlman** [comment]
Sure. The threshold seems to be around ~20-30 jobs. I am using the Session API.

**Comment by shinybrar** [comment]
Fixed in v1.0+
