### ISSUE TITLE
Headless job API misses environment variables or some string processing is going wrong? 

### ISSUE THREAD

**Issue by ErikOsinga** [CHIMEFRB/skaha#48]
Hi,

I'm not excluding the possibility that I'm simply not understanding the headless job launch API (or some deeper concepts more generally), but it seems like when I launch a headless job with the Python API, I can't find any variables, e.g.

![image](https://github.com/CHIMEFRB/skaha/assets/12582441/17546304-4e29-452b-9b97-d421bd04b84d)

Although I suspect that perhaps it has to do with the way '$' is encoded and sent as job? (Because of the strings around '$HOME' in the error message.

**Comment by shinybrar** [comment]
When working with headless containers, the command execution context differs significantly from a typical interactive shell environment. In a headless container, commands like `ls` are executed directly without loading a shell environment such as `Bash`. This can lead to unexpected behavior, especially with environment variables like `$HOME` that are typically initialized in a `Bash` session.

In a headless container, these variables might not be set as they would be in an interactive Bash environment causing commands that rely on them to fail. This is likely why the `ls` command isn't behaving as expected in your case.

To address this, you can explicitly invoke Bash when running your command,

```python
session_id = session.create(
    name="ls-test",
    image="images.canfar.net/cirada/possumpipelineheadless:v0.1",
    cores=2,
    ram=4,
    kind="headless",
    cmd="/bin/bash",
    args="-c ls $HOME"
)
```

You can also see the difference in your environment, with and without `Bash` initialization,
```python
session_id = session.create(
    name="bashless",
    image="images.canfar.net/cirada/possumpipelineheadless:v0.1",
    cores=2,
    ram=4,
    kind="headless",
    cmd="env",
)
```
```python
session_id = session.create(
    name="bashful",
    image="images.canfar.net/cirada/possumpipelineheadless:v0.1",
    cores=2,
    ram=4,
    kind="headless",
    cmd="/bin/bash",
    args="env"
)
```

**Comment by ErikOsinga** [comment]
Ah I see, I didn't realise that there's no shell environment, that's good to know, and probably also explains why I wasn't finding anything in $PATH when trying to run scripts headlessly without doing something like 'bash python.py'
